// 此文件为自动生成而成。请不要手动修改。
/**
 *
 *  API 请求名枚举列表
 */
export const enum ReqNames {
  Sigin = "Sigin",
  Logout = "Logout",
  GetUserInfo = "GetUserInfo",
  GetDepartmentList = "GetDepartmentList",
  PostDepartment = "PostDepartment",
  GetDepartment = "GetDepartment",
  PutDepartment = "PutDepartment",
  DeleteDepartment = "DeleteDepartment",
  GetProcessList = "GetProcessList",
  PostProcess = "PostProcess",
  GetDepartmentProcessList = "GetDepartmentProcessList",
  GetProcess = "GetProcess",
  PutProcess = "PutProcess",
  DeleteProcess = "DeleteProcess",
  GetQuestionList = "GetQuestionList",
  PostQuestion = "PostQuestion",
  GetDepartmentQuestionList = "GetDepartmentQuestionList",
  GetServiceQuestionList = "GetServiceQuestionList",
  PutQuestion = "PutQuestion",
  DeleteQuestion = "DeleteQuestion",
  GetServiceList = "GetServiceList",
  PostService = "PostService",
  GetSearchServiceList = "GetSearchServiceList",
  GetDepartmentServiceList = "GetDepartmentServiceList",
  GetService = "GetService",
  PutService = "PutService",
  DeleteService = "DeleteService",
  GetFile = "GetFile",
  GetUserList = "GetUserList",
  PostUser = "PostUser",
  GetUser = "GetUser",
  PutUser = "PutUser",
  DeleteUser = "DeleteUser",
  GetUserProcessList = "GetUserProcessList",
  PutUserProcess = "PutUserProcess",
  GetUserServiceList = "GetUserServiceList",
  PostUserService = "PostUserService",
  GetMyServiceList = "GetMyServiceList",
  GetDepartmentUserServiceList = "GetDepartmentUserServiceList",
  GetUserServiceDetailsList = "GetUserServiceDetailsList",
  GetUserService = "GetUserService",
  PutUserService = "PutUserService",
  DeleteUserServic = "DeleteUserServic"
}
